src/odbc.cpp

Add check for ArrayBuffer when binding values, so that now binary data can be sent through the connector

When an ArrayBuffer is passed in as a parameter, bind to SQL_C_BINARY

---

src/odbc.cpp

In addition to ArrayBuffer, add support for Buffer -> binary data as well

Adding support for Node.js Buffer class to send binary data

---

lib/odbc.d.ts
package-lock.json
package.json

Add a `.d.ts` file that contains definitions for all functions and classes exported by the `odbc` module.
Fixes #56

Typescript .d.ts

---

src/odbc.h
src/odbc_connection.cpp

Fix build warnings

---

src/odbc_connection.cpp

Add additional information from SQLDescribCol (columnSize, decimalDigits, nullable) on result sets
Resolves #98

[Feature] Add additional column information

---

CHANGELOG.md
package-lock.json
package.json
src/odbc.cpp
src/odbc_connection.cpp

[Fix] Add 2.3.3 Changelog

---

src/odbc.h

Remove unneeded odbc header files

---

lib/odbc.d.ts

Implementation of feature request issued in issue #144

added connection parameter interfaces for connect and pool functions

---

lib/Pool.js

Check maxSize before increasing pool size

---

src/odbc_connection.cpp

Allow users to pass a `timeout` property to queryOptions, which is then passed to a statement handle using `SQL_ATTR_QUERY_TIMEOUT`.

Add query timeout support

---

LICENSE
README.md
src/odbc.cpp
src/odbc.h
src/odbc_connection.cpp
src/odbc_connection.h
src/odbc_statement.cpp
src/odbc_statement.h

Update copyright to 2021

---

.github/ISSUE_TEMPLATE/bug-report.md
README.md
src/odbc.cpp
src/odbc.h
src/odbc_connection.cpp
src/odbc_cursor.cpp
src/odbc_statement.cpp

* Remove DEBUG_PRINTF statements in the code in favor of driver manager tracing
* Remove references to tracing through defining `DEBUG` in issue template
* Create a section in README.md outlining how to turn on tracing

Remove DEBUG_PRINTF statements

---

README.md

* Add a README section outlining supported Node.js versions
* Minor README cleanup

List Supported Node.js Versions

---

lib/odbc.d.ts

Closes https://github.com/markdirish/node-odbc/issues/172

Fix ColumnDefinition type

---

lib/odbc.d.ts

[Fix] Correct PoolParmeters interface (#183)

---

README.md
binding.gyp

Trivial change, just updated README with instructions for FreeBSD, and added library/include locations in bindings.gyp so that it can be built on the FreeBSD operating system.

Added support for building on FreeBSD

---

CHANGELOG.md
README.md
package-lock.json
package.json

Update CHANGELOG.md with all changes interesting to users
Update README.md with all new change (query options and Cursor mostly)
Update version in package.json and package-lock.json

Prepare for 2.4.0 Release

---

README.md

Update timeout definitions in README.md

---

src/odbc.cpp
src/odbc.h
src/odbc_connection.cpp

Change Parameter->StrLen_or_IndPtr back from pointer

---

CHANGELOG.md
README.md
package-lock.json
package.json

Creating a PR to let GitHub Actions to run as a sanity check for building on Windows and MacOS

[2.4.1] Prepare for 2.4.1 release

---

src/odbc.cpp

Fix incorrect size check causing infinite loop

---

lib/odbc.d.ts

Add type parameter in TypeScript definitions for connection's  function

---

lib/odbc.d.ts

Returns a Cursor type when specifying the cursor query option

Add TypeScript types for Cursor option

---

.github/workflows/build-binaries.yml
.github/workflows/create-release.yml

Update GitHub Actions Node.js versions

---

README.md
lib/odbc.d.ts

Signed-off-by: Myron Ng <49994092+myronng@users.noreply.github.com>

Fix typing + documentation for reuseConnections

---

README.md

Update README with Node.js 18

---

test/DBMS/ibmi/config.js
test/queries/_test.test.js

Merged in a commit, but it broke some tests the check the column definitions returned.

Fix tests for previous PR

---

.github/workflows/build.yml
.github/workflows/create-release.yml
.gitignore

- Install unixodbc in homebrew on macOS
- Add descriptive names to steps
- Rename build-binaries
Also fix gitignore to only ignore build* directories.

Clean up GitHub Actions workflows
