IBM/node-odbc

package-lock.json, src/odbc.h
@markdirish -
Here's the fix for the compilation issue we're seeing on Windows. Specifically, I'm using Windows 10. Please let me know if this is able to be merged.
Thanks,
Ryan
=> Fix for Windows std::max compilation issue.

src/odbc.cpp
SQL_FLOAT was not targeted to SQL_C_DOUBLE in binding the columns, instead defaulting on SQL_C_CHAR. When it came out, it was assumed to be SQL_C_DOUBLE, resulting in 8 bytes of char gibberish. Added to switch statement to fix.
For some numbers bound to SQL_C_CHAR, there would be the potential for garbage data if an additional byte wasn't added to hold a null terminator ('\0').
Fixes wankdanker#67
Fixes #8
=> Fixing both an SQL_FLOAT issue and boundRow garbage Data

README.md, package.json, src/odbc.h, src/odbc_connection.cpp, test/connection/callProcedure.js
There was an error in callProcedure, and fixing some typos and adding information to README. Because this also includes the previous PR that includes important data fixes, bumping npm version to release.
=> Fixing callProcedure, updating README, bumping to v2.0.0-3

binding.gyp
The build was failing on Mac because n-api exceptions were not disabled or configured
=> Update binding.gyp to fix failing build on Mac

package-lock.json, package.json, src/odbc.cpp
Giving ArrayBuffer data a finalizerCallback, data should remain valid until ArrayBuffer goes out of scope.
Bump to version 2.1.1
=> Fix array buffer

src/odbc.cpp, src/odbc.h, src/odbc_connection.cpp, src/odbc_statement.cpp, src/odbc_statement.h, test/test.js
* Redo how errors are returned by adding an odbcErrors array. This array has objects that have 3 fields: state, code, and message. The state is the SQL State that ODBC returns, while the code and message are from the driver.
* Add the ability to return data from fetching with arrays instead of just objects
* Added a ton of DEBUG messages
=> Redo errors

CHANGELOG.md, binding.gyp, lib/Pool.js, package.json, src/odbc_connection.cpp
When really hammering the Pool, occasionally the CloseAsyncWorker would be called before the QueryAsyncWorker destructor, which would call a segfault. Did a check that the connection handle is not `SQL_NULL_HANDLE` before freeing the statement handles.
=> Fixing a seg fault and improving the Pool

README.md
odbc.connect(connectionString (error, connection) .... is missing a comma.
It should be odbc.connect(connectionString, (error, connection)
=> Update READ.me to correct select documentation

lib/Statement.js
Fix missing Statement odbcErrors detail when an error is thrown asynchronously (matches callback errors). Prior to the fix, Statement errors that are thrown using `async` inadvertently remove vital `odbcErrors` that are included when using their _callback_ counterparts.
=> Fix missing Statement odbcErrors when an error is thrown async

src/odbc_statement.cpp
Added more descriptive bind parameter details in errors to indicate the number of bind parameters in the statement vs what was passed into the bind.
=> Show the statement bind parameter counts in errors

lib/Connection.js, lib/Pool.js
Calling `new Error()` in JavaScript around the error passed from N-API causes all of the information to be lost except the `message` property. We want to retain the `odbcErrors` property that holds an array of ODBC diagnostic records. Simply need to reject with the error returned from N-API instead of wrapping in a `new` call.
=> [2.3.0] Fix 'new Error'

.github/workflows/build-binaries.yml, .github/workflows/create-release.yml, package-lock.json, package.json
* Add `node-pre-gyp` dependency to download pre-built binaries when possible
* Create 2 GitHub Actions:
1. `build-binaries.yml` runs on pushes and pull requests, builds the binaries on Windows, MacOS, and Linux to ensure that the package builds correctly.
2. `create-release.yml` runs on pushing with a `v*` tag, creates a new release and packages up pre-built binaries for `node-pre-gyp` to find.
=> 2.3.0 actions

.github/workflows/create-release.yml, .gitignore, binding.gyp, lib/Pool.js, lib/odbc.js, package.json
`node-pre-gyp` has the capability to build binaries that target N-API versions (which are ABI stable), and not Node ABI versions. In order to take advantage of all of that, we have to change how the binaries are bound and required in the .js files, how they are built, and how they are declared in `package.json`. To the end user, everything should remain the same, there are just a few extra steps along the way.
This will allow binaries to be built for operating systems / architectures / N-API versions, and then during the install process it will attempt to find appropriate binaries for the system on the GitHub page's release artifacts.
=> 2.3.0 fix actions

src/odbc_connection.cpp
When calling stored procedures with output parameters, the output is
always blank. This is due to using the wrong size field when querying
SQLProcedureColumns to retrieve the column size for each parameter. This
field is defined by ODBC as an INTEGER, but the pointer is read from a
SMALLINT instead. This results in the size being read from only the top
2 bytes of the 4 byte value. On little endian systems, this will be OK
so long as the size is < 32k. On big endian systems it will always be 0
unless the size is > 32k or negative; regardless it will always be
*wrong*.
Fixes #103
=> Fix endian bug in stored procedure output parms

.github/workflows/build-binaries.yml
When prebuilt binaries exist, ensure that the workflow builds the PR from source
=> [Fix] Make GitHub Actions build from source

binding.gyp
Update binding.gyp to build Windows with UNICODE defined by default
=> [Enhancement] Build Windows with UNICODE

src/odbc_connection.cpp
When moving from boundRow to storedRow, add space for null-terminator for SQL_C_CHAR bindings so atof() works
Fixes #96
=> [Fix] Ensure NUMERICS return correct values

package-lock.json, package.json, src/odbc.cpp, src/odbc_connection.cpp
If UNICODE is defined, have result.columns.name use char16_t
If UNICODE is defined, have error.state and error.code use char16_t
Fixes #112
=> [Fix] Fix UNICODE string

src/odbc_connection.cpp
* Fix column names in results being single characters when UNICODE is defined
* Fix statement on result object single character when UNICODE is defined
Fixes #112
=> [issue112] Fix more UNICODE issues

CHANGELOG.md, package-lock.json, package.json, src/odbc_connection.cpp
* Fix column names in results being single characters when UNICODE is defined
* Fix statement on result object single character when UNICODE is defined
Fixes #112
=> [issue112] Fix more UNICODE issues (#116)

binding.gyp, package-lock.json, package.json, src/odbc.cpp, src/odbc_connection.cpp
Update package.json so that node-addon-api is >=3.0.2 (latest)
#if NAPI_VERSION checks for all BigInts (in new node-addon-api, N-API 6 or greater is required)
Build binaries for versions 3 through 6 (nothing before or after currently enables additional functionalty)
Fixes #131 
=> [enhancement] Upgrade node-addon-api to version 3.x

lib/Connection.js, lib/Pool.js, lib/odbc.js, test/pool/close.js
* Improve how pooling is handled by having connections fire off a "connected" event once they have finished connecting.
* Also prevent the package from creating lots of connections if there are enough connections in the process of being created to handle the load (create new connections again when there is a backup of waiting connections).
=> [Fix] Improve pooling with EventEmitter and counting active connection attempts

src/odbc_connection.cpp
I noticed in a warning in a recent build that lead me to identify this bug:
```
../src/odbc_connection.cpp:362:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
362 |             switch(columns[j]->bind_type) {
|             ^~~~~~
../src/odbc_connection.cpp:372:11: note: here
372 |           case SQL_FLOAT:
|           ^~~~
```
=> Break in the correct location to prevent fallthrough

lib/odbc.d.ts
Currently I have to do this ugly type conversion:
```ts
const result = <TABLE_SCHEMA[]><unknown>(await connection.query(stmt, items));
```
To make things easier, this pull request adds a generic T to the query functions of the Connection class.
The result is a much cleaner code:
```ts
const result = await connection.query<TABLE_SCHEMA>(stmt, items);
```
=> TypeScript: Add generic type to query functions of Connection

src/odbc_connection.cpp
There is one dangling Napi::BigInt reference that isn't surrounded by an `#if NAPI_VERSION > 5`. Napi::BigInt was only standardized in NAPI_VERSION 6, so it needs to be wrapped to support versions of Node.js that are pre-version 6 ([Consult this matrix](https://nodejs.org/api/n-api.html#n_api_node_api_version_matrix))
=> Fix Napi::BigInt build error

.github/workflows/build-binaries.yml, .github/workflows/create-release.yml
* For building and testing binaries, update the Node.js version matrix to include Node.js 14.x (as well as 10.x and 12.x)
* For creating a release, update the version built on to be Node.js 14.x
=> Update GitHub Actions to include Node.js 14

src/odbc.h, src/odbc_connection.cpp
Issue: https://github.com/markdirish/node-odbc/issues/127
Current behavior is for SQL_BIGINT to bind to SQL_C_UBIGINT, which means that any negative big int will cause an error. Switch to binding to SQL_C_SBIGINT so signed bigints can be retrieved.
It might be good in the future to check whether types are signed or not using `[SQLGetTypeInfo`](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgettypeinfo-function?view=sql-server-ver15) and use the 'UNSIGNED_ATTRIBUTE' column, but that's a task for another day...
=> Signed SQL_BIGINT

src/odbc.cpp, src/odbc.h, src/odbc_connection.cpp, src/odbc_cursor.cpp, src/odbc_statement.cpp
Quick refactor PR fixing two pet peeves I have with the `StatementData` struct:
1. There is really no need to store the return code on the data structure. Instead, create a local `SQLRETURN` variable in the `Execute()` function of the `AsyncWorker`s that can be used for any call to the ODBC API made in that thread.
2. I changed the variable names of the `SQLHENV` and `SQLHDBC` to `henv` and `hdbc` respectively. I didn't change the `SQLHSTMT` because it was more ubiquitous. I change that in this PR.
I also have "vertical-ized" or "elongated" various calls to ODBC functions. It has become much easier to see what arguments are being passed in what positions this way, and I am changing them as I encounter them.
=> Refactor: Local return codes and StatementData hSTMT -> hstmt

src/odbc_connection.cpp
For WCHAR fields, buffer offsets were calculated incorrectly as the space for the null-terminator was added _after_ multiplication of the ColumnSize with the row index, instead of being added to the ColumnSize before.
Instead of wrapping the equation in parens, I decided to use `bufferSize`, which includes space for the null-terminator and is stored as bytes instead of 2-byte SQLWCHAR units, and simply divide it by `sizeof(SQLWCHAR)`. This makes it clearly what is actually happening (offsetting the memory location by the size of the buffer * the row you are trying to get from the buffer). It also matches the logic for `SQLCHAR` immediate below (except for the dividing by `sizeof` part).
Fixes #174 
=> Issue 174: Fix wchar buffers pointing at the wrong memory locations

src/odbc.cpp, src/odbc_connection.cpp
Ignore errors for SQLGetInfo calls, assigning a sane value ourselves
Ensure that maxColumnNameLength is actually being used by bind_col
Minor formatting
Fixes #128
=> Ignore errors with SQLGetInfo

package-lock.json, package.json
There were several npm vulnerabilities raised when installing the package. I ran `npm audit --fix` to get rid of all but one, which required a manual upgrade of mocha due to semver considerations. Upgrade mocha and reran the tests to ensure that everything still worked (it does, I don't do anything _too_ fancy with mocha).
=> Bump dependency versions to fix vulnerabilities

lib/Pool.js, test/pool/close.js, test/pool/constructor.js
I have tried several times to get the "create lots of connections" part of connection pooling working as I want it to; namely, allow queries to run while all of the connections are spinning up (the first query running immediately after the first connection returns). Currently, when a pool is initialized with 10 connections, those 10 connections are queued up internally in the Node.js process, and any additional async worker will get queued up behind them. This means that the first query run after a pool is initialized won't actually be started for a long time (10+ seconds in the default case). I thought that using `Promise.race` would fix the issue, but in reality it didn't have any effect since the Promises began running as soon as they were declared.
I believe this PR finally gets it …
=> Fix pool connection-creation blocking queries

src/odbc.cpp, src/odbc_connection.cpp, src/odbc_connection.h
For whatever reason, `connection.loginTimeout` had a getter _and_ a setter, when it needs to be set prior to connecting. Removed the setter, and also ensured that the getter returns whatever value was either set in the connection options, or if the driver has decided to change the option, the value that the driver changed it to.
I also removed the `connection.connectionTimeout` setter. It wasn't actually _doing_ anything, and although setting the connection timeout after connecting makes sense and is allowed, I'm not sure how best to handle the async nature of setting a new value in relation to JavaScript properties. Might need to implement a setter that is a function:
```
connection.setConnectionTimeout(value, callback?);
```
or maybe a generic one?
``` …
```
=> Clean up connection getters/setters for timeouts

lib/Pool.js, lib/odbc.js, package-lock.json, package.json
Per #192, node-pre-gyp has been deprecated and is now maintained as @mapbox/node-pre-gyp. Fix up the package.json and package-lock.json files, and references in the code.
=> Update node-pre-gyp to @mapbox/node-pre-gyp

src/odbc.cpp, src/odbc.h, src/odbc_connection.cpp
The biggest leak is from ODBCConnection::CallProcedure, which calls
deleteColumns twice after calling SQLProcedures and SQLProcedureColumns.
This function does not delete any of the boundRow array members, only
the array itself. Likewise, it clears the storedRows vector, but does
not delete any of the pointers contained within. The code to properly do
this is in the clear method, but it also clears out the bound parameters
which we need to save once we call the actual procedure. This should
probably be changed so that is not needed, but for now we can
consolidate the necessary cleanup code form clear in to deleteColumns
and the inline the rest into the destructor (since clear is only called
there) along with a call to deleteColumns.
Additionally, make sure to delete other pointers passed …
=> Fix various memory leaks and mismatched delete

README.md, lib/Pool.js, lib/odbc.d.ts, test/pool/query.js
I realized when going to close #154 that query options were never added to the `.query` function added to pools. This PR seeks to remedy that oversight.
=> Add query options to Pool.query

src/odbc.cpp
In my case, I saw only the first character of the column name and this fix solved my problem. Thanks to the author of the issue #226.
=>  Handling 0 for SQL_MAX_COLUMN_NAME_LEN

src/odbc_connection.cpp
Ran tests before pushing a new version, and came across this segfault:
When calling a procedure, the first call thats made is `SQLProcedures`. After the data is stored from that call, `data->deleteColumns()` is called. Immediately after deleting columns, need to re-call the `set_fetch_size()`, which creates the `data->row_status_array`. This array is deleted in `deleteColumns()`, so it causes a segfault without this recreation.
225/225 tests passed after this fix
=> Fixing a segfault caused by new binding code paths

src/odbc_connection.cpp
The SQL generated to in callProcedure is a standard C string, but passed
to SQLExecDirectW when UNICODE is defined. Instead, it needs to be
generated as a wide string.
Note that printf format specifies for strings on Windows are a bit
*unique* as %s means char* with printf, but wchar_t* with wprintf and
vice-versa for %S.
https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-170#type-field-characters
Fixes #120
Signed-off-by: Kevin Adler <kadler@us.ibm.com>
=> Fix callProcedure on Windows with UNICODE

src/odbc_connection.cpp
Set the first value of the parameterString to a null-byte so strcat knows where to start
=> Fix parameter string construction in procedures

lib/odbc.d.ts
Signed-off-by: Christian Marker / Intility AS <christian.marker@intility.no>
Adding missing generic return type to Statement#execute function, just as in Connection#query.
=> feat: Add generic result type to Statement#execute

src/odbc_connection.cpp
Previously it was assumed that `combinedProcedureName` was made from narrow chars, when in fact `data->catalog`, `data->schema`, and `data->procedure` are all converted to `SQLTCHAR *`s. This was causing the combined procedure name string to be all jumbled, but since everything before the final call to `SQLExecDirect` uses `SQLTCHARs` in an API, everything returned normal until the crash.
To fix, I made the `combinedProcedureName` either a `char *` or `wchar_t *` depending on whether `UNICODE` was defined, and built the final `data->sql` accordingly.
=> Fix the creation to combinedProcedureName when a procedure is called

binding.gyp
When building with Python 3.9 (eg. PYTHON=python3.9 npm i), gyp sets OS
to "os400" since Python now returns that from sys.platform. Copy the
existing IBM i config from the AIX branch and simplify since we know
it's IBM i in that branch.
Signed-off-by: Kevin Adler <kadler@us.ibm.com>
=> Add binding.gyp path for OS400

src/odbc_connection.cpp
If overwriteParams isn't initialized, a memory error can occur if the callProcedure exits early due to wrong procedure name or wrong number of parameters
`overwriteParams` is used to indicate whether a field is an `INPUT` parameter, or an `INPUT/OUT` or `OUTPUT` parameter. This is so we can preserve the Javascript value for INPUT parameters instead of trying to go JavaScript -> C type -> convert C-type based on parameter ODBC type -> C type -> JavaScript, when the value should remain constant. `overwriteParams` is only set after a successful call to `SQLProcedureColumns`, so it is currently erroring when trying to call `delete` in the structure for a pointer that was never set.
=> Initialize overwriteParams in CallProcedureAsyncWorker

README.md
The noData property for cursors is improperly documented as a method.
Signed-off-by: Myron Ng <49994092+Sooyap@users.noreply.github.com>
=> Fix cursor.noData property documentation in README

.github/workflows/create-release.yml
Previously, we only built a binary of one napi version (v3) on one operating system (Windows). Update the action so that it builds all of our built napi versions for Windows, MacOS, and Linux, and upload those prebuilt binaries to the draft release that is created
=> Build and upload binaries for all GitHub Actions runners

README.md, src/odbc_statement.cpp, test/statement/execute.test.js
Add execution timeout code path for Statement.execute
Add README.md entries for using query options with Statement.execute
Add tests to ensure setting query timeout at this point won't crash ODBC
Fixes #272 
=> Fixup Statement.execute query options

src/odbc_connection.cpp
In MS SQL Server, a field defined as VARCHAR(MAX) will return a column size of 0,
which breaks the SQLBindCol workflow. When we detect that a column size of 0 is
returned for SQL_VARCHAR, SQL_WVARCHAR, and SQL_WVARBINARY, go through the 'long_data'
path, which uses SQLGetData.
=> Fix VARCHAR(MAX) fields from SQL Server returning no data

lib/Connection.js, lib/odbc.d.ts, src/odbc.h, src/odbc_connection.cpp, src/odbc_connection.h, test/DBMS/ibmi/config.js, test/connection/_test.test.js, test/connection/foreignkeys.test.js, test/connection/primaryKeys.test.js, test/statement/execute.test.js
Good ideas coming out of #281. Wrote `primaryKeys` and `foreignKeys` functions for the Connection class. Mostly just copying the existing functionality from the `columns` and `tables` functions.
Ran test suite against it, all passed.
=> Add primaryKeys() and foreignKeys() functions on Connection

src/odbc_connection.cpp
Remove cursor declaration, which was causing extreme performance degredation.
=> Remove static cursor declaration

src/odbc_connection.cpp
When allocating the buffer for the procedure parameters, the size is cast to an SQLSMALLINT, ie. signed short. For CHAR parameters longer than 8191, the SQLSMALLINT overflows and become negative after we multiply by 4 to account for possible UTF-8 expansion. The negative value is then passed to new[]() which throws a std::bad_alloc.
I'm not sure why an SQLSMALLINT was used here, since it is only used temporarily before being stored in BufferLength, which is an SQLLEN so use that type instead. This temp variable is only needed because we need the original BufferLength to memcpy during reallocation of ParameterValuePtr.
In addition, after reallocation of ParameterValuePtr, the original pointer is never freed, leading to a memory leak. A lot of this code would be cleaned up if we replaced …
=> Fix callProcedure core dump with large parameters

package.json
This makes it easier for development to build from source by running `npm run build`.
=> feat: Add npm script to build from source

lib/odbc.d.ts, src/odbc.cpp, src/odbc_connection.cpp
Export all data types on the main package export object.
Return a dataTypeName property on result objects. The new structure of an object in the `columns` property of the return object looks like:
```javascript
{
name: 'CUSNUM',
dataType: 2,
dataTypeName: 'SQL_NUMERIC',
columnSize: 6,
decimalDigits: 0,
nullable: false
},
{
name: 'LSTNAM',
dataType: 1,
dataTypeName: 'SQL_CHAR',
columnSize: 8,
decimalDigits: 0,
nullable: false
}
```
If user's need the _native_ data type name that can be used in SQL statements, instead of the generic ODBC data type name, they can call `.columns` on the connection object, which returns values in the result set like:
```javascript
...
TYPE_NAME: 'NUMERIC'
...
```
Fixes #332
=> Improve program dataType(name) access

lib/odbc.d.ts, src/odbc_connection.cpp
Add `null` type for all nullable parameters
Fixes Connection.query callback implementation
Change Result<unknown> to use generic types (matches `query` implementation)
Remove callback signatures from Promise implementations
Fix table error messages in `odbc_connection.cpp`
=> Improve typing in `odbc.d.ts`

src/odbc_connection.cpp
Previously, setting SQL_CURSOR_STATIC was fixed for the prepare/bind/execute workflow, but not for just calling .query. This PR fixes it for calling a Connection's .query as well
=> Remove `SQL_CURSOR_STATIC` statement attribute from Connection.query

.github/stale.yml
- Bump from 30 to 90 days
- Add "confirmed" label to keep issue from being marked stale
- Prevent issues being marked stale if they're in projects, milestones, or are assigned
The confirmed label (or whatever we want to call it) will need to be created. Alternatively, we should probably switch to [actions/stale](https://github.com/actions/stale) since Stale Bot is deprecated and unmaintained.
=> Tame down stale bot

binding.gyp
As discussed in #380 , I believe the `NAPI_EXPERIMENTAL` flag is causing build issues on supported node versions for this package.
I've looked through the git blame, and it appears that `NAPI_EXPERIMENTAL` was added a number of years ago for `BigInt` support. `BigInt` support was added to node in version 10, and this package says it supports 12, 14, 16 and 18.  
So I think it's safe to remove `NAPI_EXPERIMENTAL` which will fix some failures on node version `18.20+` and other things.
Fixes #380
=> remove NAPI_EXPERIMENTAL

package.json, src/odbc.cpp, src/odbc_connection.cpp
This allows us to only build for one NAPI version instead of 4 and removes a separate code path for NAPI versions older than 6. We technically don't use anything newer than 6, but may as well go to 8 since that supports all Node.js versions we care about (and even some we don't).
https://nodejs.org/api/n-api.html#node-api-version-matrix
=> Drop support for NAPI 7 and below

.github/Jenkinsfile, .github/fix-node-pre-gyp-windows.js, .github/upload-release-asset.js, .github/workflows/build.yml, .github/workflows/create-release.yml, package-lock.json, package.json
- Refactor and clean up GitHub Actions workflows to automatically create and publish a release upon tag creation
- Add automation for building the IBM i binaries using Jenkins
- Build both arm64 and x86_64 macOS binaries
- Build for oldest supported OS targets
- Publish NPM package
=> Prepare release automation

lib/Cursor.js
- the noData getter threw the wrong Error Reference
- CURSOR was misspelled CUSROR
- The cb param was documented as callback
=> Fix various typos and reference issues in Cursor.js
